Makefile: use regular SYSD_DIR for LuneOS as well
* and allow it to be set from outside

* fixes:
ERROR: waydroid-1.4.2+git-r0 do_package: QA Issue: waydroid: Files/directories were installed but not shipped in any package:
  /lib
  /lib/systemd
  /lib/systemd/system
  /lib/systemd/system/waydroid-container.service
  /lib/systemd/system/waydroid-init.service
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
waydroid: 5 installed and not shipped files. [installed-vs-shipped]

when e.g. usrmerge is used and systemd_unitdir="/usr/lib/systemd"
and waydroid didn't respect that and installed the files in /lib/systemd
instead.

Allow to set SYSD_DIR from outside with EXTRA_OEMAKE to use:
systemd_system_unitdir="/usr/lib/systemd/system"
like the most of other recipes do.

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>